version: '3.7'
services:
  backend:
    container_name: orderapi
    image: 192.168.1.120:5000/order-api:1
    restart: always
    networks:
      - appserver_network
    ports:
      - "8080:8080"
    environment:
      - "DENV=prod"
  frontend:
    container_name: orderui
    image: 192.168.1.120:5000/order-ui:1
    restart: always
    networks:
      - appserver_network
    ports:
      - "3000:3000"
networks:
  appserver_network:
    external: true