spring:
  application:
    name: order-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://192.168.1.150:5432/homexpnzdb
    username: postgres
    password: 1pass56

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    allowed-origins: 
      - http://localhost:3000
      - https://hmxp.northvue.xyz
      - https://hmxpapi.northvue.xyz

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
